[1] Added to the README.txt file a link to the SVN repository, so that Setuptools can automatically find the development version when asked to install the "-dev" version of zc.recipe.cmmi.
[2] Applied fix for bug #261367 i.e. changed open() of file being downloaded
to binary, so that errors like the following no longer occur under MS Windows.

  uncompress = self.decompress.decompress(buf)
  error: Error -3 while decompressing: invalid distance too far back



git-svn-id: svn://svn.zope.org/repos/main/zc.recipe.cmmi/trunk@92694 62d5b8a3-27da-0310-9561-8e5933582275